<?xml version="1.0" encoding="utf-8"?><Database Name="HotelBookingMan" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MAYURESHB;Initial Catalog=HotelBookingMan;Persist Security Info=True;User ID=sa" SettingsObjectName="UserManagementOperation.Properties.Settings" SettingsPropertyName="HotelBookingManConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserInfo" Member="UserInfos">
    <Type Name="UserInfo">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spBookingDetails" Method="spBookingDetails">
    <Parameter Name="BookingId" Parameter="bookingId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="HotelId" Parameter="hotelId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="CheckInDate" Parameter="checkInDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CheckOutDate" Parameter="checkOutDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertHotel" Method="spInsertHotel">
    <Parameter Name="HotelID" Parameter="hotelID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="HotelName" Parameter="hotelName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="EmailId" Parameter="emailId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TotalRooms" Parameter="totalRooms" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="AvailableRooms" Parameter="availableRooms" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertCustomer" Method="spInsertCustomer">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="EmailId" Parameter="emailId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spInsertCustomerResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spInsertUser" Method="spInsertUser">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="EmailId" Parameter="emailId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spInsertUserResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectBookingDetail" Method="spSelectBookingDetail">
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="spSelectBookingDetailResult">
      <Column Name="BookingId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CheckInDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CheckOutDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectBookingDetail_new" Method="spSelectBookingDetail_new">
    <Parameter Name="BookingId" Parameter="bookingId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="spSelectBookingDetail_newResult">
      <Column Name="BookingId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CheckInDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CheckOutDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectCustomer" Method="spSelectCustomer">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spSelectCustomerResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectHotel" Method="spSelectHotel">
    <Parameter Name="HotelName" Parameter="hotelName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spSelectHotelResult">
      <Column Name="HotelId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="HotelName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalRooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableRooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectHotel2" Method="spSelectHotel2">
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spSelectHotel2Result">
      <Column Name="HotelId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="HotelName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalRooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableRooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>